import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>baby elon musk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/elon.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Namito Yokota
        </h1>

        <p className={styles.description}>
          Coming around mid-march maybe
        </p>
      </main>
    </div>
  )
}

export default Home
